### ISSUE TITLE
Clarity on names.md

### ISSUE THREAD

**Issue by ryanznie** [DS219/spark-seprep#9]
https://github.com/DS219/spark-seprep/blob/ab7bfea06d7d27f3c340865628f7f8d7b5fc50c1/assignments/assignment3/assignment3.md?plain=1#L20

I thought it would be more clear if instead of \<Their Name.md> it would be \<P2 Name.md>

Same thing with line 52. Our group was a little confused at first so we did each other's names.

 https://github.com/DS219/spark-seprep/blob/ab7bfea06d7d27f3c340865628f7f8d7b5fc50c1/assignments/assignment3/assignment3.md?plain=1#L52

**Comment by aakankshaduggal** [comment]
I apologize for the confusion @ryanznie 
Just add your name file to the folder.
For you, it will be `ryan.md`
